list=[]
list.append("A")
list.append("B")
list.append("C")
print(list)
list.insert(1,"D")
print(list)
a=[1,2,3]
b=["Hello","How","Are","You"]
a.extend(b)
print(a)
c=("Computer")
a.extend(c)
print(a)
a.remove("Hello")
print(a)
print(a.pop())
a.reverse()
print(a)
